import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "../components/Nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Skip link for keyboard users */}
        <a href="#main-content" className="skip-link absolute left-2 top-2 z-50 bg-foreground text-background px-3 py-1 rounded -translate-y-8 focus:translate-y-0 focus:outline-none">
          Skip to content
        </a>

        <div className="min-h-screen flex flex-col">
          <Nav />
          <main id="main-content" className="flex-1">{children}</main>
          <footer>
            <div className="max-w-4xl mx-auto px-6 py-6 text-sm text-center text-gray-400">
              © {new Date().getFullYear()} Claire Han
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
